[package]
name = "fsm"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2"
cargo = { version = "0.63" }
clap = { version = "3.2.16", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6.8"
itertools = "0.10"
once_cell = "1"
tempfile = "3.3"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread", "process", "fs"] }
toml_edit = "0.14"
tracing = "0.1.36"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
owo-colors = "3"
