[package]
name = "fsm"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2"
clap = { version = "3.2.17", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6.8"
itertools = "0.10"
once_cell = "1"
owo-colors = "3"
reqwest = "0.11"
serde_json = "1.0.83"
serde = { version = "1.0.143", features = ["derive"] }
tempfile = "3.3"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["macros", "sync", "rt-multi-thread", "process", "fs", "io-util"] }
tracing = "0.1.36"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
xdg = "2"