name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Check rustfmt
      run: nix develop --command cargo fmt -- --check

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    # Runs clippy as part of the preBuild.
    - name: Build
      run: nix build -L
    - name: Patch the interpreter to work on Ubuntu
      run: |
        cp result/bin/fsm fsm
        chmod u+w fsm
        nix develop -c patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 fsm
    - name: Create artifact for fsm
      uses: actions/upload-artifact@v3
      with:
        name: fsm
        path: |
          fsm

  FsmShell:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download prebuilt fsm
      uses: actions/download-artifact@v3
      with:
        name: fsm
    - name: Run `fsm --help`
      run: |
        chmod +x fsm
        ./fsm --help

  Spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: codespell-project/codespell-problem-matcher@v1
    - name: Check Spelling
      run: nix develop --command codespell --ignore-words-list crate,pullrequest,pullrequests,ser .

  NixFormatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Check nixpkgs-fmt formatting
      run: nix develop --command sh -c "git ls-files '*.nix' | xargs nixpkgs-fmt --check"

  EditorConfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: greut/eclint-action@v0
