name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  NixFlakeCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/flake-checker-action@v4
        with:
          fail-mode: true

  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check rustfmt
        run: nix develop --command ci-check-rustfmt

  Spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check Spelling
        run: nix develop --command ci-check-spelling

  NixFormatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check nixpkgs-fmt formatting
        run: nix develop --command ci-check-nixpkgs-fmt

  RegistryFormatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check registry.json formatting
        run: nix develop --command ci-check-registry-format

  EditorConfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check EditorConfig conformance
        run: nix develop --command ci-check-editorconfig

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Run tests
        run: nix develop --command ci-test-rust
        # run: nix develop -c -- cargo test -- --include-ignored

  BuildX86Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      # Runs clippy as part of the preBuild.
      - name: Build riff
        run: nix build .#packages.x86_64-linux.riff -L
      - name: Build riffStatic
        run: nix build .#packages.x86_64-linux.riffStatic -L
      - name: Create artifact for x86_64-linux riffStatic
        uses: actions/upload-artifact@v3
        with:
          name: riff-x86_64-linux
          path: |
            result/bin/riff

  BuildX86Darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      # Runs clippy as part of the preBuild.
      - name: Build riff
        run: nix build .#packages.x86_64-darwin.riff -L
      - name: Create artifact for x86_64-darwin riff
        uses: actions/upload-artifact@v3
        with:
          name: riff-x86_64-darwin
          path: |
            result/bin/riff

  RiffShell:
    needs: BuildX86Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download prebuilt riff
        uses: actions/download-artifact@v3
        with:
          name: riff-x86_64-linux
      - name: Run `riff --help`
        run: |
          chmod +x riff
          ./riff --help
